name: adaptive-comfort
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.4.5
  - numpy
  - pandas
  - xlsxwriter
  - black
  - pytest
