name: adaptive_comfort_docs
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - conda-forge
#  - http://10.10.30.125:8000
dependencies:
  - python
  - numpy
  - pandas
  - xlsxwriter
  - markdown
  - nodejs
  - pyyaml
  - pytest
  - jupyter-book # for docs
  - sphinx # for docs
  - sphinx-book-theme # for docs
  - sphinx-autoapi
  - sphinxcontrib-mermaid
